notifications:
  email: false
language: python
python: 
  - 2.7
  - 3.6
cache: pip
install:
  - pip install -e .[dev]
  - pip install tox-travis coveralls
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="unittests"
script: 
  - "./run_ci_tests.sh"
after_success:
  - reentry dev coveralls
