notifications:
    email: false
language: python
python: 
 - 2.7
 - 3.6
cache: pip
install:
    - pip install --upgrade -e .[dev]
    - pip install tox-travis
env:
    - TEST_TYPE="pre-commit"
    - TEST_TYPE="unittests"
script: "./run_ci_tests.sh"
