notifications:
  email: false
language: python
python: 
  - 2.7
  - 3.6
cache: pip
install:
  - pip install -e .[dev]
  - pip install tox-travis coveralls
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="unittests"
script: 
  - if [ "$TEST_TYPE" == "unittests" ] ; then ./run_tests.sh ; fi
  - if [ "$TEST_TYPE" == "pre-commit" ] ; then pre-commit run --all-files || ( git diff; pip freeze | grep yapf; exit 1; ) ; fi

after_success:
  - if [ "$TEST_TYPE" == "unittests" ] ; then reentry dev coveralls; fi
